spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec-pizza
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: pupi.yh@gmail.com
    password: lvmgmuhfyclwctdg
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
server:
  servlet:
    context-path: /ec-pizza
stripe:
  public:
    key: pk_test_51Kg19vEHPP3PCUKNoNktBYftlWHvfUW48tnNoRR5LzxWsjT4ZJnc0AhfkT02enNweSf3PXonyUOd6SoAaTRBBGkf00KgUJP1B4
  secret:
    key: sk_test_51Kg19vEHPP3PCUKN6GgzjmJeZ0M9VNaluCLX7ckmj8QppMDLs49wusImtZj7hfYEedlMG99wV7TGEBzajbmO0ej500ZUXH1cKk
